nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

httpTimeout: 300000
httpRetry: 3
httpRetryDelay: 1000

# 캐시 설정
enableGlobalCache: true
cacheFolder: ./.yarn/cache

# 네트워크 최적화
preferInteractive: false
enableTelemetry: false

# 로깅
logFilters:
  - code: YN0013
    level: discard
